barkochba/urls.py
from django.conf.urls import patterns, url

from barkochba import views

urlpatterns = patterns('',
	url(r'^$', views.main, name='main'),
	url(r'^update-people/$', views.story_update_people, name='update_people'),
)

export/urls.py
from django.conf.urls import patterns, url

from export import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	# pl: /export/3/
	url(r'^(?P<camp_id>\d+)/$', views.camp_export, name='camp_export'),
)

home/urls.py
from django.conf.urls import patterns, url

from home import views

urlpatterns = patterns('',
	url(r'^$', views.home_redirect, name='home_redirect'),
)

matektabor/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'matektabor.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),

	url(r'^', include('home.urls', namespace="home")),
	url(r'^barkochba/', include('barkochba.urls', namespace="barkochba")),
	url(r'^tabor/', include('tabor.urls', namespace="tabor")),
	url(r'^export/', include('export.urls', namespace="export")),
	url(r'^admin/', include(admin.site.urls)),
)

barkochba/models.py
from django.db import models
from django.forms import ModelForm
from tabor.models import Person



class Story(models.Model):
	# Sorszam a dokumentumban
	order_number = models.PositiveIntegerField(
		u'Sorsz\u00E1m',
		default=0)
	# A tortenet rovid cime
	title = models.CharField(
		u'C\u00EDm',
		max_length=200)
	# Maga a tortenet amit elmondunk
	story = models.TextField(
		u'T\u00F6rt\u00E9net',
		default=u'?')
	# A teljes megoldas
	solution = models.TextField(
		u'Megold\u00E1s',
		default=u'?')
	# Azok, akik mar hallottak korabban
	people = models.ManyToManyField(Person, blank=True)

	class Meta:
		verbose_name = u'Barkochbat\u00F6rt\u00E9net'
		verbose_name_plural = u'Barkochbat\u00F6rt\u00E9net'

	def __unicode__(self):
		return self.title

	def people_sorted(self):
		return self.people.order_by('name')

class StoryForm(ModelForm):
	class Meta:
		model = Story
		fields = '__all__'

barkochba/views.py
import json
from django.shortcuts import render
from django.http import HttpResponse, Http404

from tabor.models import Person
from barkochba.models import Story, StoryForm
from szobabeosztas.models import Camp, Room


def main(request):
	all_person_list = Person.objects.all()
	all_person_json = get_select2_json_for_people(all_person_list)
	all_person_json_string = json.dumps(all_person_json)

	all_camps = Camp.objects.order_by('group__name', 'number')
	camps = []
	for camp in all_camps:
		camp_map = {}
		camp_map['camp'] = camp
		camp_map['camp_name'] = camp.get_name()
		camp_map['rooms'] = Room.objects.filter(camp__id=camp.id).order_by('name')
		camps.append(camp_map)

	all_rooms = Room.objects.all();
	room_list_with_people = []
	for room in all_rooms:
		person_ids = [x for x in room.people.values_list('id', flat=True)];
		room_list_with_people.append({"id": room.id, "person_ids": person_ids})
	rooms_json = json.dumps(room_list_with_people)

	story_list = Story.objects.order_by('order_number')
	stories = []
	storiesWithZeroOrderNumber = []
	for story in story_list:
		person_ids = story.people.values_list('id', flat=True)
		person_ids_json = '[' + ', '.join(str(person_id) for person_id in person_ids) + ']'
		related_person_list = story.people.all()
		related_person_json = get_select2_json_for_people(related_person_list)
		related_person_json_string = json.dumps(related_person_json)
		story_map = {}
		story_map['story'] = story
		story_map['person_ids_json'] = person_ids_json
		story_map['related_people_json'] = related_person_json_string
		if story.order_number == 0:
			storiesWithZeroOrderNumber.append(story_map)
		else:
			stories.append(story_map)
	stories.extend(storiesWithZeroOrderNumber)
	context = {
		'stories': stories,
		'all_people_json': all_person_json_string,
		'camps': camps,
		'rooms_json': rooms_json,
		'export_people': json.dumps(all_person_list),
		'export_stories': json.dumps(story_list),
		'export_camps': json.dumps(all_camps),
		'export_rooms': json.dumps(all_rooms)
	}
	return render(request, 'barkochba/main.html', context)


def story_update_people(request):
	storyId = request.POST.get('storyId')
	addPersonIds = parse_set_of_ints(request.POST.get('addPeople'))
	removePersonIds = parse_set_of_ints(request.POST.get('removePeople'))

	# addPersonIds and removePersonIds should be disjoint, but for safety
	# we exclude elements in their intersection.
	intersectionIds = addPersonIds & removePersonIds;
	addPersonIds = addPersonIds - intersectionIds;
	removePersonIds = removePersonIds - intersectionIds;

	story = Story.objects.get(pk = storyId)
	personIds = set([p.id for p in story.people.all()])
	# Only add the missing ones.
	addPersonIds = addPersonIds - personIds;
	# Only remove the present ones.
	removePersonIds = removePersonIds & personIds;

	addPeopleObjects = Person.objects.filter(pk__in = addPersonIds)
	for personObject in addPeopleObjects:
		story.people.add(personObject);

	removePeopleObjects = Person.objects.filter(pk__in = removePersonIds)
	for personObject in removePeopleObjects:
		story.people.remove(personObject);

	story.save()
	return HttpResponse()


def parse_set_of_ints(setString):
	if setString == '':
		return set([])
	intStrings = setString.split(',')
	intSet = set([])
	for intString in intStrings:
		try:
			parsedInt = int(intString)
			intSet.add(parsedInt)
		except ValueError:
			pass
			#TODO: Log the parsing error somewhere.
	return intSet


def get_select2_json_for_people(person_list):
	person_list_json = [{'id': int(p.id), 'text': unicode(p.get_name_with_camp_group())} for p in person_list]
	return person_list_json

barkochba/templates/barkochba/main.html
{% load staticfiles %}
{% csrf_token %}

<link rel="stylesheet/less" type="text/css" href="{% static 'barkochba/style.less' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'lib/select2-3.5.1/select2.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'lib/bootstrap-3.2.0/css/bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'lib/bootstrap-3.2.0/css/bootstrap-theme.css' %}" />

<script src="{% static 'lib/jquery-2.1.1.js' %}" type="text/javascript"></script>
<script src="{% static 'lib/jquery.cookie-1.4.1.js' %}" type="text/javascript"></script>
<script src="{% static 'lib/select2-3.5.1/select2.js' %}"></script>
<script src="{% static 'lib/select2-3.5.1/select2_locale_hu.js' %}"></script>
<script src="{% static 'lib/less-1.7.5.js' %}" type="text/javascript"></script>
<script src="{% static 'lib/underscore-1.7.0.js' %}" type="text/javascript"></script>
<script src="{% static 'lib/handlebars-v2.0.0.js' %}" type="text/javascript"></script>
<script src="{% static 'lib/bootstrap-3.2.0/js/bootstrap.js' %}" type="text/javascript"></script>
<script src="{% static 'lib/notify.js' %}" type="text/javascript"></script>

<script type="text/javascript">

var personJsonData = {{ all_people_json|safe }};

var exportPeople = {{ export_people|safe }};
var exportStories = {{ export_stories|safe }};
var exportCamps = {{ export_camps|safe }};
var exportRooms = {{ export_rooms|safe }};

function _namesChanged() {
	selectedPersonIdsString = $("#names-input").val();
	selectedPersonIds = _.map(selectedPersonIdsString.split(','), function (value) {
		return Number(value);
	});
	$('a.barkochba-story-summary').each(function() {
		$(this).removeClass('alert-warning');
		$(this).removeClass('alert-danger');
		storyPersonIds = $(this).data("person-ids");
		heardStoryPersonIds = _.intersection(selectedPersonIds, storyPersonIds);
		if (heardStoryPersonIds.length >= 3) {
			$(this).addClass('alert-danger');
		} else if (heardStoryPersonIds.length >= 1) {
			$(this).addClass('alert-warning');
		}
	});
}

function _campChanged() {
	$("#names-input").select2("data", [], true);
	selectedCampId = $("#camp-select").val();
	$('div.room-select-container').hide();
	$('.room-select').val("");
	$('div.room-select-container').filter(function (index) {
		return $(this).data("camp-id") == selectedCampId;
	}).show();
}

function _roomChanged(roomselect) {
	var roomsJsonData = {{ rooms_json|safe }}
	if (roomselect.value == "") {
		$("#names-input").select2("data", [], true);
		return;
	}
	roomId = Number(roomselect.value)
	room = _.find(roomsJsonData, function(item) {
		return item.id === roomId;
	});
	people = _.filter(personJsonData, function(person) {
		return _.contains(room.person_ids, person.id);
	});
	$("#names-input").select2("data", people, true);
}

function _storySelected(storyId) {
	// Select the summary
	$('a.barkochba-story-summary').removeClass('active');
	storySummary = $('a.barkochba-story-summary').filter(function (index) {
		return $(this).data("story-id") === storyId;
	});
	console.log("selected story:", storySummary);
	storySummary.addClass('active');
	storyPersonIds = storySummary.data("person-ids");
	console.log("related people:", storySummary.data("person-ids"));
	
	_initStoryDetails(storyId, storyPersonIds);

	// Show the details
	$('div.barkochba-story-detail').hide();
	$('div.barkochba-story-detail').filter(function (index) {
		return $(this).data("story-id") === storyId;
	}).show();
}

function _initStoryDetails(storyId, storyPersonIds) {
	relatedPersonJsonData = _.filter(personJsonData, function(person) {
		return _.contains(storyPersonIds, person.id);
	});
	var namesInputId = "#names-input-" + storyId;
    $(namesInputId).select2({
    	placeholder: "Keress egy személy nevére",
    	allowClear: true,
    	minimumInputLength: 1,
    	multiple: true,
    	data:{ results: personJsonData }
	});

    // Prepopulating with the existing people
	$(namesInputId).select2(
		"data",
		relatedPersonJsonData
	);

	var relatedPeopleSaveButtonId = "#related-people-save-button-" + storyId;
	$(namesInputId).on("change", function() {
		$(relatedPeopleSaveButtonId).prop("disabled", false);
	});

	$(relatedPeopleSaveButtonId).on("click", function() {
		trySaveStoryPeople(storyId, relatedPeopleSaveButtonId, 'bottom left', true);
	});

	var storyToldButtonId = "#story-told-button-" + storyId;
	$(storyToldButtonId).on("click", function() {
		var new_people = $("#names-input").select2("data");
		var existing_people = $(namesInputId).select2("data");
		var all_people = _.union(existing_people, new_people);
		$(namesInputId).select2("data", all_people);

		trySaveStoryPeople(storyId, storyToldButtonId, 'bottom right', false);
	});
}

$(document).ready(function () {
    $("#names-input").select2({
    	placeholder: "Keress egy személy nevére",
    	allowClear: true,
    	minimumInputLength: 1,
    	multiple: true,
    	data:{ results: personJsonData }
	});

	$("#names-input").on("change", _namesChanged);

	$("#camp-select").on("change", _campChanged);
	$('div.camp-select-container').show();

	$('.room-select').on("change", function() {
		_roomChanged(this);
	});

	$("#save-all-button").on("click", saveAllModifications);
});

function saveAllModifications() {
	$("#save-all-panel").hide();
	$('a.barkochba-story-summary').each(function() {
		var personIds = $(this).data("person-ids");
		var originalPersonIds = $(this).data("original-person-ids");
		var addPersonIds = _.difference(personIds, originalPersonIds);
		var removePersonIds = _.difference(originalPersonIds, personIds);

		if (addPersonIds.length == 0 && removePersonIds.length == 0) {
			return;
		}
		storyId = $(this).data("story-id");
		postUpdatePeople(
			storyId,
			addPersonIds,
			removePersonIds,
			function(data) {
				console.log('A mentés sikerült');
				console.log(data);
				$("#success-notification-area").notify("A mentés sikeres volt!",
				{
				  position: 'bottom left',
				  className: 'success'
				}
			);
			},
			function(data) {
				console.log('A mentés nem sikerült');
				console.log(data);
				$("#save-all-panel").show("slow");
				$("#save-all-button").notify("A mentés sikertelen!",
					{
					  position: 'bottom left',
					  className: 'error'
					}
				);
			}
		);
	});
}

function trySaveStoryPeople(storyId, buttonId, notificationPosition, disableButton) {
	saveStoryPeople(
		storyId,
		function(data) {
			console.log('A mentés sikerült');
			console.log(data);
			if (disableButton) {
				$(buttonId).prop("disabled", true);
			}
			$(buttonId).notify("A mentés sikeres volt!",
				{
				  position: notificationPosition,
				  className: 'success'
				}
			);
		},
		function(data) {
			console.log('A mentés nem sikerült');
			console.log(data);
			$(buttonId).notify("A mentés sikertelen!",
				{
				  position: notificationPosition,
				  className: 'error'
				}
			);
			$("#save-all-panel").show("slow");
		}
	);
}

// Saves the people currently in the name selector box as the people
// who heard this Story
function saveStoryPeople(storyId, successFunction, errorFunction) {
	console.log("Saving people for story:", storyId);
	var peopleData = $("#names-input-" + storyId).select2("data");
	console.log(peopleData);
	var personIds = _.map(peopleData, function(person) {return person.id;});
	console.log("input person ids:", personIds);

	// We always send the total diff compared to the state when the page was loaded.
	var originalPersonIds = $("#story-summary-" + storyId).data("original-person-ids");
	console.log("original person ids:", originalPersonIds);
	var addPersonIds = _.difference(personIds, originalPersonIds);
	console.log("person ids to add:", addPersonIds);
	var removePersonIds = _.difference(originalPersonIds, personIds);
	console.log("person ids to remove:", removePersonIds);

	$("#story-summary-" + storyId).data("person-ids", personIds);
	postUpdatePeople(storyId, addPersonIds, removePersonIds, successFunction, errorFunction);
}

function postUpdatePeople(storyId, addPersonIds, removePersonIds, successFunction, errorFunction) {
	var csrftoken = $.cookie('csrftoken');
	var jqxhr = $.ajax({
		url: "{% url 'barkochba:update_people' %}",
		type: "POST",
		data: {'storyId': storyId.toString(), 'addPeople': addPersonIds.toString(), 'removePeople': removePersonIds.toString()},
		traditional: true,
		beforeSend: function(xhr, settings) {
			xhr.setRequestHeader("X-CSRFToken", csrftoken);
		},
		success: successFunction,
		error: errorFunction
	});
}
</script>

<body>

	<div class="container">
		<div class="row name-selection-row">
			<div class="col-sm-4">
				<div>
					<h3>Nekik mesélek:</h3>
					<p>Válaszd ki a tábort és a szobát, vagy írd be azon gyerekek neveit, akiknek mesélni szeretnél. Ezután a listában színesek lesznek azok a barkochbatörténetek, amiket valamelyik gyerek már hallotta.</p>
					<p><a href="{% url 'export:index' %}">Áttekintő táblázatok az egyes táborokhoz</a></p>
				</div>
			</div>
			<div class="col-sm-3 col-lg-2">
				<div class="camp-select-container">
					<select class="form-control" id="camp-select" style="width: 100%;">
						<option value="" selected>Válassz tábort</option>
						{% for camp_map in camps %}
							<option value="{{ camp_map.camp.id }}">{{ camp_map.camp_name }}</option>
						{% endfor %}
					</select>
				</div>
			</div>
			<div class="col-sm-3 col-lg-2">
				{% for camp_map in camps %}
					<div class="room-select-container" data-camp-id="{{ camp_map.camp.id }}">
						<select class="form-control room-select" id="room-select-{{ camp_map.camp.id }}" style="width: 100%;">
							<option value="" selected>Válassz szobát</option>
							{% for room in camp_map.rooms %}
								<option value="{{ room.id }}">{{ room.name }}</option>
							{% endfor %}
						</select>							
					</div>
				{% endfor %}
			</div>

			<div class="col-sm-8">
				<div class="names-input-container">
						<p><input type='hidden' id="names-input" style="width: 100%;" /></p>
				</div>
			</div>
		</div>

		<div class="row story-row">
			<div class="col-sm-4 barkochba-story-list-column">
				<div class="list-group">
					{% for story_map in stories %}
						<a href="#" class="list-group-item barkochba-story-summary" id="story-summary-{{ story_map.story.id }}" data-story-id="{{ story_map.story.id }}" data-person-ids="{{ story_map.person_ids_json }}" data-original-person-ids="{{ story_map.person_ids_json }}" onclick="_storySelected({{ story_map.story.id }});">
							{% if story_map.story.order_number != 0 %}{{ story_map.story.order_number }} - 	{% endif %}{{story_map.story.title }}
						</a>
					{% endfor %}
				</div>
			</div>

			<div class="col-sm-8 barkochba-story-detail-column">

				<div id="success-notification-area"></div>
				<div class="panel panel-default save-all-notification" id="save-all-panel">
					<div class="panel-body alert-danger">
						<p>
							<strong>Nem mentett módosításaid vannak!</strong> Ezek mentéséhez kattints ide:
						</p>
						<button type="button" id="save-all-button" class="btn btn-danger">Összes mentése</button>		
					</div>
				</div>

				{% for story_map in stories %}
					<div class="panel panel-default barkochba-story-detail" data-story-id="{{ story_map.story.id }}">
						<div class="panel-heading">
							<h3 class="panel-title">
								{% if story_map.story.order_number != 0 %}{{ story_map.story.order_number }} - 	{% endif %}{{story_map.story.title }}
							</h3>
						</div>
						<div class="panel-body">
							<div class="story-detail-done-button">
								<button type="button" id="story-told-button-{{ story_map.story.id }}" class="btn btn-success">
										<span class="glyphicon glyphicon-ok"></span> Elmeséltem
								</button>
							</div>

							<p>
								{{ story_map.story.story|linebreaks }}
							</p>

							<!--<button type="button" class="btn btn-default" data-toggle="collapse" data-target="#story-{{ story_map.story.id }}-solution">
								Megoldás
							</button>-->

							<div class="panel panel-default">
								<div class="panel-heading">
									<a href="#" data-toggle="collapse" data-target="#story-{{ story_map.story.id }}-solution">
										Megoldás
									</a>
								</div>
								<div class="collapse" id="story-{{ story_map.story.id }}-solution">
									<div class="panel-body">
										{{ story_map.story.solution|linebreaks }}
									</div>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<a href="#" data-toggle="collapse" data-target="#story-{{ story_map.story.id }}-related-people-div">
										Akik ismerik
									</a>
								</div>
								<div class="collapse" id="story-{{ story_map.story.id }}-related-people-div">
									<div class="panel-body">
										<div class="related-names-input-container">
											<input type='hidden' id="names-input-{{ story_map.story.id }}" style="width: 100%;" />
										</div>
										<button disabled type="button" id="related-people-save-button-{{ story_map.story.id }}" class="btn btn-sm btn-default">
											<span class="glyphicon glyphicon-saved"></span> Mentés
										</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>

	</div>

</body>