export/urls.py
from django.conf.urls import patterns, url

from export import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	# pl: /export/3/
	url(r'^(?P<camp_id>\d+)/$', views.camp_export, name='camp_export'),
)

home/urls.py
from django.conf.urls import patterns, url

from home import views

urlpatterns = patterns('',
	url(r'^$', views.home_redirect, name='home_redirect'),
)

matektabor/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'matektabor.views.home', name='home'),
	# url(r'^blog/', include('blog.urls')),

	url(r'^', include('home.urls', namespace="home")),
	url(r'^barkochba/', include('barkochba.urls', namespace="barkochba")),
	url(r'^tabor/', include('tabor.urls', namespace="tabor")),
	url(r'^export/', include('export.urls', namespace="export")),
	url(r'^admin/', include(admin.site.urls)),
)

export/models.py
from django.db import models

# Create your models here.

szobabeosztas/models.py
from django.db import models
from tabor.models import Person, CampGroup


class Camp(models.Model):
	# A tabori csoport.
	group = models.ForeignKey(CampGroup, verbose_name = u'Csoport')

	# A tabor sorszama, nem feltetlenul szam, lehet pl. Extra1 stb.
	number = models.CharField(
		u'Sorsz\u00E1m',
		max_length=200)

	class Meta:
		verbose_name = u'T\u00E1bor'
		verbose_name_plural = u'T\u00E1borok'

	def get_name(self):
		return self.group.name + '/' + self.number

	def __unicode__(self):
		return self.get_name()



class Room(models.Model):
	# A tabor, amelyikhez ez a szoba tartozik.
	camp = models.ForeignKey(Camp, verbose_name = u'T\u00E1bor')

	# Szobaszam/nev, pl.: B, 112 stb.
	name = models.CharField(
		u'Szoban\u00E9v',
		max_length=200)

	# A szoba lakoi.
	people = models.ManyToManyField(Person, blank=True, verbose_name = u'Lak\u00F3k')	

	class Meta:
		verbose_name = u'Szoba'
		verbose_name_plural = u'Szob\u00E1k'

	def get_name(self):
		return self.camp.get_name() + '/' + self.name

	def __unicode__(self):
		return self.get_name()

export/views.py
from django.shortcuts import get_object_or_404, render

from szobabeosztas.models import Camp, Room
from barkochba.models import Story

def try_parse_int(s, default_val=-1):
  try:
    return int(s)
  except ValueError:
    return default_val

def index(request):
	camp_list = Camp.objects.order_by('group__name', 'number')
	context = {'camp_list': camp_list}
	return render(request, 'export/index.html', context)

def camp_export(request, camp_id):
	camp = get_object_or_404(Camp, pk=camp_id)
	rooms = camp.room_set.all()
	requested_room_ids = [try_parse_int(s) for s in request.GET.getlist('room')]
	if requested_room_ids:
		rooms = camp.room_set.filter(id__in=requested_room_ids)
	include_descriptions = request.GET.get('description', '0') == '1'
	include_solutions = request.GET.get('solution', '0') == '1'
	story_list = Story.objects.order_by('order_number')
	stories = []
	storiesWithZeroOrderNumber = []
	for story in story_list:
		story_map = {}
		story_map['story'] = story
		story_map['people'] = story.people.all()
		story_map['rooms'] = []
		for room in rooms:
			room_people_ids = room.people.all().values('id')
			people = story.people.filter(id__in=room_people_ids).order_by('name')
			if (not people):
				continue
			room_map = {}
			room_map['room'] = room.name
			room_map['people'] = people
			story_map['rooms'].append(room_map)
		if story.order_number == 0:
			storiesWithZeroOrderNumber.append(story_map)
		else:
			stories.append(story_map)
	stories.extend(storiesWithZeroOrderNumber)
	context = {
		'stories': stories,
		'camp': camp,
		'include_descriptions': include_descriptions,
		'include_solutions': include_solutions
	}
	return render(request, 'export/camp_export.html', context)

export/templates/export/camp_export.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>{{ camp.get_name }} barkochbatörténet ismeretek</title>
<style type="text/css">
p {
	font-family: "Times New Roman";
	font-size: 10pt;
	margin: 0;
}
p.story-title {
	font-family: "Times New Roman";
	font-size: 12pt;
	margin: 0;
}
p.title {
	text-align: center;
	font-family: "Times New Roman";
	font-size: 14pt;
	font-weight: normal;
	margin: 6pt;
}
table {
	table-layout: fixed;
	width: 100%;
	border: 1px solid black;
	border-collapse: collapse;
}
td {
	width: 50%;
	border: 1px solid black;
}
</style>
</head>

<body>
<p class="title">{{ camp.get_name }} barkochbatörténet ismeretek</p>
<table>
	{% for story_map in stories %}
		<tr>
			<td>
				<p class="story-title">
					{% if story_map.story.order_number != 0 %}{{ story_map.story.order_number }} - {% endif %}{{ story_map.story.title }}
				</p>
				{% if include_descriptions and story_map.story.story != '?' %}
					{{ story_map.story.story|linebreaks}}
				{% endif %}
				{% if include_solutions and story_map.story.solution != '?' %}
					{{ 'M: '|add:story_map.story.solution|linebreaks}}
				{% endif %}
			</td>
			<td>
				{% for room_map in story_map.rooms %}
					<p class="room-people">
						{{ room_map.room }}:
						{% for person in room_map.people %}{% if forloop.counter0 > 0 %}, {% endif %}{{ person.name }}{% endfor %}
					</p>
				{% endfor %}
			</td>
		</tr>
	{% endfor %}
</table>

</body>
</html>

export/templates/export/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'lib/bootstrap-3.2.0/css/bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'lib/bootstrap-3.2.0/css/bootstrap-theme.css' %}" />
<script src="{% static 'lib/jquery-2.1.1.js' %}" type="text/javascript"></script>
<script src="{% static 'lib/bootstrap-3.2.0/js/bootstrap.js' %}" type="text/javascript"></script>

<div class="container">
	<div class="row">
		<h3>Tábor választás</h3>
		<p>Válaszd ki az alábbi listából azt a tábort, aminek a szobabeosztásával szeretnéd generálni a táblázatot a barkochbatörténet ismeretekről. Ha nincs a listában a tábor, az azt jelenti, hogy nincs felvéve hozzá szobabeosztás.</p>
	</div>
	<div class="row">
		<table class="table">
		{% for camp in camp_list %}
		<tr>
			<td class="col-sm-4" style="border: none">
				<a class="list-group-item" href="{% url 'export:camp_export' camp.id %}?description=1&amp;solution=1">{{ camp.get_name }}</a>
			</td>
			<td class="col-sm-8" style="border: none">
				<div class="panel panel-default">
					<div class="panel-heading"><a role="button" data-toggle="collapse" href="#form-{{ camp.id }}">Opciók</a></div>
					<div class="panel-body collapse" id="form-{{ camp.id }}">
						<form role="form" action="{% url 'export:camp_export' camp.id %}" method="get">
							<div class="checkbox"><label><input type="checkbox" name="description" value="1" checked>Legyenek benne a történetek leírásai</label></div>
							<div class="checkbox"><label><input type="checkbox" name="solution" value="1" checked>Legyenek benne a megoldások</label></div>
							<div class="form-group">
								Csak a következő szobák:<label class="checkbox-inline"> </label>
								{% for room in camp.room_set.all %}
									<label class="checkbox-inline"><input type="checkbox" name="room" value="{{ room.id }}">{{ room.name }}</label>
								{% endfor %}
							</div>
							<button type="submit" class="btn btn-default">Táblázat generálása</button>
						</form>
					</div>
				</div>
			</td>
		</tr>
		{% endfor %}
		</table>
	</div>
</div>